from pydantic import BaseModel, Field, constr
from typing import Optional, Dict, Any, List
from datetime import datetime, timezone
from bson import ObjectId


class ActiveHours(BaseModel):
    """Active hours configuration for heartbeat scheduling."""
    start: str = Field(..., pattern=r"^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$")  # HH:MM format
    end: str = Field(..., pattern=r"^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$")  # HH:MM format
    timezone: Optional[str] = None  # IANA timezone string, e.g. "America/New_York"


class HeartbeatConfig(BaseModel):
    """Configuration for proactive heartbeat system."""
    enabled: bool = True
    interval: str = "2h"  # e.g. "1h", "30m", "2h"
    active_hours: Optional[ActiveHours] = None
    model_name: str = "anthropic/claude-haiku-4-5"
    max_insights_per_day: int = 5


class ProactiveInsight(BaseModel):
    """A proactive insight generated by the heartbeat system."""
    id: Optional[str] = Field(None, alias="_id")
    user_id: str = "default"
    insight_type: str  # "task_suggestion", "goal_reminder", "follow_up"
    title: constr(strip_whitespace=True, min_length=1, max_length=200)
    description: constr(strip_whitespace=True, min_length=1, max_length=1000)
    action_data: Optional[Dict[str, Any]] = None
    dismissed: bool = False
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    class Config:
        populate_by_name = True
        json_encoders = {
            ObjectId: str,
            datetime: lambda dt: dt.isoformat()
        }


class InsightCreatePayload(BaseModel):
    """Payload for creating a new insight."""
    insight_type: str
    title: constr(strip_whitespace=True, min_length=1, max_length=200)
    description: constr(strip_whitespace=True, min_length=1, max_length=1000)
    action_data: Optional[Dict[str, Any]] = None


class HeartbeatConfigUpdate(BaseModel):
    """Payload for updating heartbeat configuration."""
    enabled: Optional[bool] = None
    interval: Optional[str] = None
    active_hours: Optional[ActiveHours] = None
    model_name: Optional[str] = None
    max_insights_per_day: Optional[int] = None
