import pytest
import asyncio
from datetime import datetime, timezone
from fastapi.testclient import TestClient
from unittest.mock import patch, MagicMock
import croniter

from main import app
from core.models import ScheduledTaskPayload, TaskSchedule
from services.task_scheduler import scheduler

client = TestClient(app)

class TestScheduledTasks:
    """Test scheduled tasks functionality including frontend-backend communication"""

    def test_create_scheduled_task_simple_daily(self):
        """Test creating a daily scheduled task (simulating frontend simple scheduler)"""
        # This simulates what the frontend sends for "Daily at 9:00 AM"
        payload = {
            "name": "Daily Report",
            "goal": "Generate daily status report",
            "schedule": {
                "cron_expression": "0 9 * * *",  # Daily at 9 AM (generated by frontend)
                "timezone": "UTC",
                "enabled": True
            }
        }
        
        with patch.object(scheduler, 'schedule_task', return_value="test_task_id") as mock_schedule:
            response = client.post("/api/scheduled-tasks", json=payload)
            
            assert response.status_code == 200
            data = response.json()
            assert data["id"] == "test_task_id"
            assert data["message"] == "Scheduled task created successfully"
            
            # Verify the scheduler was called with correct data
            mock_schedule.assert_called_once()
            call_args = mock_schedule.call_args[0][0]
            assert call_args["name"] == "Daily Report"
            assert call_args["schedule"]["cron_expression"] == "0 9 * * *"

    def test_create_scheduled_task_simple_weekly(self):
        """Test creating a weekly scheduled task (Monday at 2:30 PM)"""
        # This simulates frontend generating: "Weekly on Monday at 2:30 PM"
        payload = {
            "name": "Weekly Review",
            "goal": "Conduct weekly team review",
            "schedule": {
                "cron_expression": "30 14 * * 1",  # Monday at 2:30 PM
                "timezone": "America/New_York",
                "enabled": True
            }
        }
        
        with patch.object(scheduler, 'schedule_task', return_value="weekly_task_id") as mock_schedule:
            response = client.post("/api/scheduled-tasks", json=payload)
            
            assert response.status_code == 200
            data = response.json()
            assert data["id"] == "weekly_task_id"

    def test_create_scheduled_task_simple_monthly(self):
        """Test creating a monthly scheduled task (15th at 10:00 AM)"""
        # This simulates frontend generating: "Monthly on 15th at 10:00 AM"
        payload = {
            "name": "Monthly Report",
            "goal": "Generate monthly financial report",
            "schedule": {
                "cron_expression": "0 10 15 * *",  # 15th of month at 10 AM
                "timezone": "UTC",
                "enabled": True
            }
        }
        
        with patch.object(scheduler, 'schedule_task', return_value="monthly_task_id") as mock_schedule:
            response = client.post("/api/scheduled-tasks", json=payload)
            
            assert response.status_code == 200

    def test_create_scheduled_task_advanced_cron(self):
        """Test creating a task with advanced cron expression"""
        # This simulates frontend advanced mode: "Every weekday at 8:30 AM"
        payload = {
            "name": "Weekday Standup",
            "goal": "Send daily standup reminder",
            "schedule": {
                "cron_expression": "30 8 * * 1-5",  # Weekdays at 8:30 AM
                "timezone": "America/Los_Angeles",
                "enabled": True
            }
        }
        
        with patch.object(scheduler, 'schedule_task', return_value="advanced_task_id") as mock_schedule:
            response = client.post("/api/scheduled-tasks", json=payload)
            
            assert response.status_code == 200

    def test_invalid_cron_expression(self):
        """Test that invalid cron expressions are rejected"""
        payload = {
            "name": "Invalid Task",
            "goal": "This should fail",
            "schedule": {
                "cron_expression": "invalid cron",  # Invalid cron
                "timezone": "UTC",
                "enabled": True
            }
        }
        
        response = client.post("/api/scheduled-tasks", json=payload)
        
        assert response.status_code == 400
        assert "Invalid cron expression" in response.json()["detail"]

    def test_frontend_time_conversion_scenarios(self):
        """Test various time conversion scenarios from frontend"""
        test_cases = [
            # (description, cron_expression, expected_valid)
            ("9:00 AM daily", "0 9 * * *", True),
            ("11:45 PM daily", "45 23 * * *", True),
            ("12:00 PM (noon) daily", "0 12 * * *", True),
            ("12:00 AM (midnight) daily", "0 0 * * *", True),
            ("3:15 PM on Sundays", "15 15 * * 0", True),
            ("6:30 AM on 1st of month", "30 6 1 * *", True),
        ]
        
        for description, cron_expr, should_be_valid in test_cases:
            payload = {
                "name": f"Test {description}",
                "goal": "Test task",
                "schedule": {
                    "cron_expression": cron_expr,
                    "timezone": "UTC",
                    "enabled": True
                }
            }
            
            with patch.object(scheduler, 'schedule_task', return_value="test_id"):
                response = client.post("/api/scheduled-tasks", json=payload)
                
                if should_be_valid:
                    assert response.status_code == 200, f"Failed for {description}: {cron_expr}"
                else:
                    assert response.status_code == 400, f"Should have failed for {description}: {cron_expr}"

    def test_list_scheduled_tasks(self):
        """Test listing scheduled tasks"""
        mock_tasks = [
            {
                "_id": "task1",
                "name": "Daily Task",
                "goal": "Daily work",
                "schedule": {
                    "cron_expression": "0 9 * * *",
                    "timezone": "UTC",
                    "enabled": True
                },
                "created_at": datetime.now(timezone.utc),
                "run_count": 5,
                "last_run": None,
                "next_run": None
            }
        ]
        
        with patch('db.scheduled_tasks_crud.list_scheduled_tasks', return_value=mock_tasks):
            response = client.get("/api/scheduled-tasks")
            
            assert response.status_code == 200
            data = response.json()
            assert len(data) == 1
            assert data[0]["name"] == "Daily Task"
            assert data[0]["schedule"]["cron_expression"] == "0 9 * * *"

    def test_delete_scheduled_task(self):
        """Test deleting a scheduled task"""
        task_id = "test_task_id"
        
        with patch('db.scheduled_tasks_crud.delete_scheduled_task', return_value=True) as mock_delete:
            response = client.delete(f"/api/scheduled-tasks/{task_id}")
            
            assert response.status_code == 200
            mock_delete.assert_called_once_with(task_id)

    def test_cron_validation_edge_cases(self):
        """Test edge cases in cron validation"""
        invalid_crons = [
            "60 9 * * *",    # Invalid minute (60)
            "0 25 * * *",    # Invalid hour (25)
            "0 9 32 * *",    # Invalid day (32)
            "0 9 * 13 *",    # Invalid month (13)
            "0 9 * * 8",     # Invalid weekday (8)
            "* * * *",       # Too few fields
        ]
        
        for invalid_cron in invalid_crons:
            payload = {
                "name": "Invalid Test",
                "goal": "Should fail",
                "schedule": {
                    "cron_expression": invalid_cron,
                    "timezone": "UTC",
                    "enabled": True
                }
            }
            
            response = client.post("/api/scheduled-tasks", json=payload)
            assert response.status_code == 400, f"Should reject invalid cron: {invalid_cron}"

    def test_timezone_support(self):
        """Test that various timezones are accepted"""
        timezones = [
            "UTC",
            "America/New_York",
            "America/Chicago", 
            "America/Denver",
            "America/Los_Angeles",
            "Europe/London",
            "Asia/Tokyo"
        ]
        
        for tz in timezones:
            payload = {
                "name": f"Task in {tz}",
                "goal": "Test timezone",
                "schedule": {
                    "cron_expression": "0 9 * * *",
                    "timezone": tz,
                    "enabled": True
                }
            }
            
            with patch.object(scheduler, 'schedule_task', return_value="test_id"):
                response = client.post("/api/scheduled-tasks", json=payload)
                assert response.status_code == 200, f"Failed for timezone: {tz}"

class TestFrontendBackendIntegration:
    """Test that frontend time picker values correctly convert to backend cron expressions"""
    
    def test_am_pm_conversion(self):
        """Test AM/PM time conversions match expected cron expressions"""
        test_cases = [
            # (hour_12, minute, ampm, expected_24h_hour)
            ("1", "00", "AM", "1"),
            ("12", "00", "AM", "0"),   # Midnight
            ("12", "00", "PM", "12"),  # Noon
            ("1", "00", "PM", "13"),
            ("11", "30", "PM", "23"),
            ("6", "45", "AM", "6"),
        ]
        
        for hour_12, minute, ampm, expected_hour in test_cases:
            # Simulate frontend conversion logic
            hour_24 = int(hour_12)
            if ampm == "PM" and hour_24 != 12:
                hour_24 += 12
            if ampm == "AM" and hour_24 == 12:
                hour_24 = 0
            
            expected_cron = f"{minute} {hour_24} * * *"
            
            payload = {
                "name": f"Test {hour_12}:{minute} {ampm}",
                "goal": "Time conversion test",
                "schedule": {
                    "cron_expression": expected_cron,
                    "timezone": "UTC",
                    "enabled": True
                }
            }
            
            with patch.object(scheduler, 'schedule_task', return_value="test_id"):
                response = client.post("/api/scheduled-tasks", json=payload)
                assert response.status_code == 200, f"Failed for {hour_12}:{minute} {ampm} -> {expected_cron}"

    def test_simple_schedule_types(self):
        """Test that all simple schedule types generate valid cron expressions"""
        # Simulate frontend simple scheduler options
        schedule_types = [
            ("daily", "0 9 * * *"),
            ("weekly", "0 9 * * 1"),    # Monday
            ("monthly", "0 9 1 * *"),   # 1st of month
        ]
        
        for schedule_type, expected_cron in schedule_types:
            payload = {
                "name": f"Test {schedule_type}",
                "goal": f"Test {schedule_type} scheduling",
                "schedule": {
                    "cron_expression": expected_cron,
                    "timezone": "UTC",
                    "enabled": True
                }
            }
            
            with patch.object(scheduler, 'schedule_task', return_value="test_id"):
                response = client.post("/api/scheduled-tasks", json=payload)
                assert response.status_code == 200, f"Failed for {schedule_type}: {expected_cron}"
